config/routes.rb
Rails.application.routes.draw do
  root 'charlie#index'
  resources :compliments, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compliment.rb
class Compliment < ApplicationRecord
  validates :message, presence: true, length: { minimum: 3, maximum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charlie_controller.rb
class CharlieController < ApplicationController

  def index
    @compliments = Compliment.all
  end

  def show
    @compliment = Compliment.find_by_id(params[:id])
  end
end

app/controllers/compliments_controller.rb
class ComplimentsController < ApplicationController

  def new
    @compliment = Compliment.new
  end

  def create
    @compliment = Compliment.create(compliment_params)
    if @compliment.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end 
  end

  def show
    @compliment = Compliment.find_by_id(params[:id])
  end

  private

  def compliment_params
    params.require(:compliment).permit(:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charlie_helper.rb
module CharlieHelper
end

app/helpers/compliments_helper.rb
module ComplimentsHelper
end

app/views/charlie/index.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="text-center">
      <h1>Charlie the Westie-Poo</h1>
      <p>The cutest dog in world. The happiesst fellow around.</p>
    </div>
  </div>
  <div class="text-center">
  <h3>He loves to cuddle. He loves to play. He's the man.</h3>
  </div>
  <br /> <br />
<div class="charlie-face col-6 offset-3">
  <%= image_tag 'Charlie.jpg', class: 'img-fluid' %>
  <br />

  <div class="comp-button float-left">
    <%= link_to 'Compliment Charlie!', new_compliment_path %>
  </div>
</div>
<br />
<br />

<div class="jumbotron">
  <% @compliments.each do |compliment| %>
    <div class="text-center">
      <p class="message"><%= compliment.message %></p>
    </div>
  <% end %>

</div>

app/views/compliments/new.html.erb
<div class="text-center col-10 offset-1 praise-box">

  <h1 class="comp-header">Compliment Charlie!</h1>
  <small><%= link_to 'I just want to see that face again...', root_path%></small>
  <%= simple_form_for @compliment do |f| %>
    <%= f.input :message %>
    <%= f.submit "Compliment!", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Charlie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    

    <%= yield %>
  </body>
</html>